baseurl = "https://cogdog.github.io/cc-cert-hugo/"
title = "CC Core Certification"
languageCode = "en-us"
theme = "hugo-theme-learn"
author = "Alan Levine"
description = "Demo for CC Certification rendered via md"
publishDir = "docs"