baseURL = "https://cogdog.github.io/cc-cert-hugo/"
title = "CC Core Certification"
languageCode = "en-us"
theme = "hugo-theme-learn"
publishDir = "docs"
canonifyURLs = true

[params]

description = "Demo for CC Certification rendered via md"

[author]
  author = "Alan Levine"
  homepage = "http://cogdog.github.io/"
